### ISSUE TITLE
Update Indexing of Pandas Objects to the New Version

### ISSUE THREAD

**Issue by ahbills** [oemof/oemof-solph#1093]
In the current oemof-solph version, several future warnings are triggered during use because of the recent change to pandas indexing: using .loc[] and .iloc[] instead of simply indexing with [] and running .__getitem__. In a future pandas version, the [] indexing method will not be possible so it is important to update this. 

I'm new to oemof-solph and working with a repository in general so forgive me if I am not going about this the right way

**Comment by p-snft** [comment]
Hi @ahbills, thanks for offering support. The way you are doing it is perfectly right. I think a lot of this is already fixed in the dev branch. However, the old indexing is still used in some parts.

If you start working on this, It would be great to have a pull request right from the start, so that everybody can see the progress to avoid double work.

**Comment by p-snft** [comment]
I don't see any more warnings, seems to be solved.
