### ISSUE TITLE
Subnetworks 

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#577]
I think it would be good to have a simple interface to create sub-networks.

Imagine a power plant that consists of a heat source (e.g. solar thermal), a thermal storage and a heat engine. Additionally, there the option to convert is power to heat and store it in the same heat storage. To improve the overview, one could wrap these components in a "thermal power plant" subnetwork, and (only) view flows into and out of this subnetwork.

Of course, this can be done manually, but I see many more applications where some "grouping" shorthand neglecting internal flows would help. (Maybe, there is a mechanism I do not know, yet.)

**Comment by joroeder** [comment]
Hi, I like the idea and would support doing that - although I don't know how to do that yet. Maybe that's a topic for the next meeting?

**Comment by FranziPl** [comment]
I thought about it too, and like the idea. But I also don't have an idea, how to do so.
I think, it is not only helpful (or necessary), if you want to include the storage and the heat engine, even for modeling the collector, I need a source and a transfomer (to consider the electrical consumption of the pumps).
We (@jnnr and I) talked about requierements, the input and the output structur of such subnetworks and want to share our thoughts. It is related to #594 , because also for subnetworks, the input structur has to be defined.

Like @p-snft said, we want a collection of solph-components, that should work like a single component. If you use it, you only want to and have to create one object.
1. So these are **requirements**, we see:
 - only input and output-Flows should be visible as Flows
 - internal flows are a variable of the coponent (see 3. output api)
 - internal constrains should be possible (see 3. output api)
 - precalculations should be external? --> see facades-discussion

2. For the **input structur**, we see the same question as for the facades: should the attributes of components be renamed? Here are the two possibilities: 

    input api:
```
    solar_collector(
    label='name',
    inputs={bus_el: Flow()},
    outputs={bus_el: Flow()},
    other kwargs
    ...
    )
```
 vs. specifically named flows (like for the generic_CHP):
```
    solar_collector(
    label='name',
    electrical_pump_power={bus_el: Flow()},
    heat_output={bus_el: Flow()},
    other kwargs
    ...
    )
```
conclusion: we vote for the second option, because it is a way to distinguish different inputs or outputs, which would not be possible with the inputs-attribute.
Here it would be good to check inputs (e.g. correct number of flows passed).

3. **output api**

 - internal variables would be returned in results similar to what GenericCHP does, e.g.:
    ('solar_collector', None, curtailment)
 - only flows connecting to buses outside the subnetwork would have keys like
    ('solar_collector', 'bus_thermal', flow)

What do you think about it?

**Comment by p-snft** [comment]
I ended up having lists of sets of flow labels that I append to:

```Python
flow_list = []
bus1 = Bus(label="label1")
bus2 = Bus(label="some_label", inputs={bus1: Flow()})
flow_list.append((bus1.label, bus2.label))
```

Later I can now easily sum over all inbound/ outbound flows. As I consider this method is superior, I will close this issue.
