### ISSUE TITLE
actual_value and fixed=False

### ISSUE THREAD

**Issue by jakob-wo** [oemof/oemof-solph#631]
The Flow attributes `actual_value` and `fixed` do only make sense beeing used together if `fixed=True`. In case of `fixed=False` the `actual_value` will be ignored without an error message beeing raised.
Therefore I propose to add another error message to the collection of  `# Checking for impossible attribute combinations` in the Flow and to clearify in the documentation that `fixed=False` leads to  `actual_value` is ignored.

**Comment by jakob-wo** [comment]
Yes, this is definetely related to #547. But I got the impression that the discussion was stuck and I was rather looking for a solution that would be feasible in any of the discussed ways. 

Let me elaborate where my motivation is coming from: I have a student working with oemof for the first time. In his energy system he was using a Source to model negative residual load (aka surplus electricity) that can be consumed for free whenever available. As the energy system also incorporates invest-objects he was used to provide a timeseries with relative values for the `actual_value`, to provide a scalar for the `nominal_value` and to set `fixed=True`. Everything worked fine!
Now he wanted to change the boundary condition. Instead of "forcing the use of the neg. residual load" (flow_from_surplus_source == `actual_value` * `nominal_value`) he wanted to leave the dicision until what amount the available electricity is used to the solver. So he left everything as before but only changed the `fixed` attribute to `fixed=False`, expecting that it would result in: 0 <= flow_from_surplus_source <= `actual_value` * `nominal_value`. But it does not because `actual_value` is beeing ignored.
That behavior is not intuitive to a beginner (and neither it is to me) and when I had a look in the documentation about the Source/Sink and the usage of `fixed` I find it not clear about the consequences when using `fixed=False`.

However, I agree with you @uvchik that removing `fixed` would avoid such a misunderstanding.
Till then an error message could serve beginners well.

**Comment by uvchik** [comment]
1. Let us wait for @simnh, because I do not know enough about his motives
2. I agree that it is not totally obvious but I wonder how one could expect a parameter called `actual_value` to be the maximum value, the more as there exists a `max` parameter. Nevertheless, we should try to make it as clear as possible.

**Comment by jakob-wo** [comment]
> how one could expect a parameter called actual_value to be the maximum value

Well, it was not `actual_value` he expected to be the maximum but the product `actual_value*nominal_value`. If it is your intention to model a maximum value right from the beginning, you might start with the `max` argument as you find it in documentation. But when you have a fixed flow in a working simulation and just want to loose the fixed condition you expect that flicking the switch from True to False will just lead to the opposite behavior which is "unfixing" or loosing the condition.
I mean, I even found myself woundering a moment about that behavior until I could explaine what the mistake was. So at least let us raise an error message and add an additional line in the documentation of the Source/Sink.

**Comment by uvchik** [comment]
You are right, setting `fixed=False` will `unfix` or loosen the condition.

We have to discuss if the `actual_value` should  be used for anything else (in the future). If not, I totally agree that it is not very convenient or even confusing that one need to set another attribute to `True`. I that case it would be enough to just set the parameter in my opinion.

I am sceptical about an error message, because it is allowed. We had a long discussion about raising an error message for things that are allowed but might be unwanted. But we do not know if they are unwanted.

In the windpowerlib we had the same discussion, so we created our own WindpowerlibUseWarning. This warning is raised if a user uses the windpowerlib in a not typical way. Advanced users can easily switch this warning off and use it only for debugging. This could be a compromise.

But let's wait for the results in #547.

**Comment by jakob-wo** [comment]
Thanks for the explanation, that is an interesting point you are mentioning about the error messages and I like the idea of having something like the WindpowerlibUseWarning in oemof.solph.

>let's wait for the results in #547.

I agree !

**Comment by uvchik** [comment]
Done!
