### ISSUE TITLE
'SolverStatus' error

### ISSUE THREAD

**Issue by ciaradunks** [oemof/oemof-solph#713]
I've just cloned the oemof-solph repository (branch 585b123e3dc02b191fead4d202ba60c057c473fd), and when I try to run examples from SMOOTH, I am receiving this error, which I think is to do with oemof-solph but I'm not completely sure:   

File "C:/Users/ciara.dunks/smooth/smooth/examples/run_smooth_example.py", line 10, in <module>
    smooth_result, status = run_smooth(mymodel)
  File "C:\Users\ciara.dunks\smooth\smooth\framework\run_smooth.py", line 77, in run_smooth
    oemof_results = model_to_solve.solve(solver='cbc', solve_kwargs={'tee': False})
  File "C:\Users\ciara.dunks\oemof-solph\oemof\solph\models.py", line 204, in solve
    status = solver_results["Solver"][0]["Status"].key
AttributeError: 'SolverStatus' object has no attribute 'key'

If anyone has any ideas what could be causing it that would be really helpful, thanks.

**Comment by uvchik** [comment]
Please upgrade to the latest version of oemof.solph:

`pip install oemof.solph --upgrade`

If it does not work you should clean your virtual environment and reinstall `solph`.

**Comment by ciaradunks** [comment]
I've just tried reinstalling and I'm using v0.4.1 and v5.7 pyomo, but it still is returning the same error. Could it be to do with the branch of oemof solph that I am using?

**Comment by uvchik** [comment]
It seems to me, that you are NOT using a virtual environment for your solph installation. The path in your error message should look like this `your_virtual_env/lib/python3.8/site-packages/oemof/solph`. According to your error message you are still using a local version and an older version.

Please install a new and clean virtual environment (search the web or ask a friend/colleague if you do not know how to do it).
Install oemof.solph and SMOOTH in this virtual environment and make sure that you use the python version of this virtual environment when you execute your examples.

We definitely fixed the bug, caused by the new Pyomo version [here](https://github.com/oemof/oemof-solph/pull/710/files#diff-dfae8d6be6d152f9510d10fde34cd459) and released it with v0.4.1. There is no "key" attribute in version v0.4.1 anymore.

**Comment by ciaradunks** [comment]
Okay thanks, I think where I am confused is that I have to use this particular branch of oemof-solph for SMOOTH because it contains a component that hasn't been released to the main version yet, but I will ask someone about it. Thanks for the quick reply
