### ISSUE TITLE
GenericCHP bug when total power loss at max. output power is higher than at min. output power

### ISSUE THREAD

**Issue by c-franz** [oemof/oemof-solph#744]
Hi,
there is a bug in the GenericCHP component in oemof-solph.

When i create a motoric chp where the total power loss at the maximum output power point is higher than the power loss at the minimum output power point, then the motoric chp does not produce any output power.

I have added the motoric chp example file from the oemof examples and only changed the following two lines to produce the bug:

```
H_L_FG_share_max=[0.11 for p in range(0, periods)],
H_L_FG_share_min=[0.10 for p in range(0, periods)],
```

I used the latest release: oemof-solph 0.4.1

The complete example file is attached.
[motoric_chp.zip](https://github.com/oemof/oemof-solph/files/5886960/motoric_chp.zip)

**Comment by simnh** [comment]
Hey @c-franz ,
 
that sounds strange. however I am not involved to much in the CHP modelling and @ckaldemeyer is currently not good reachable. Does it work with other configurations, e.g. same losses ?

@ckaldemeyer Do you have an idea / possible explanation?
@fwitte  Or maybe you know something about this ?

**Comment by c-franz** [comment]
> Does it work with other configurations, e.g. same losses ?

Yes, when the losses at minimum and maximum chp operating points are the same, than it works.

I changed some other parameter values of this chp component and as far as i can tell,
the error only occurs when the losses at the maximum operating point _"H_L_FG_share_max"_ is higher than the losses at the minimum operating point.

**Comment by fwitte** [comment]
I remember that I stumbled across this issue some time ago. For some reason, the slope of the min line must always be steeper than the slope of the max line. I will dig into my files and ask my colleagues, if they remember.

**Comment by fwitte** [comment]
I've found kind of a solution here, although I do not know if it is intended to work like this. In order to make this work, changes are required in the oemof-solph core.

Our original purpose of such a feature was to have a left side restriction `> 0 W` for the `heat_output` for an extraction turbine plant with steeper inclination of the left side line than the right side line. This was due to an additional constraint in the underlying power plant model, that the plant should only be operated at a minimum fuel utilization rate or higher, leading to a PQ diagram as follows.

![ccet_Q_CW_max](https://user-images.githubusercontent.com/20252362/109008465-a5528300-76ad-11eb-9a8b-92c3cf0f4a01.png)

In contrast to the usual diagram of an extraction turbine.

![ccet](https://user-images.githubusercontent.com/20252362/109008508-b3080880-76ad-11eb-8164-fc019dd350bd.png)

To apply this change for the combustion engine, we have to add the following parameters to the model.

- A parameter we called `Q_CW_max` on the heat_output bus, that describes the maximum condenser load to cooling water in an extraction plant. For your application this parameter would be a virtual parameter you'd have to determine mathematically from the PQ data of the actual plant (so the PQ diagram of solph matches the PQ diagram of your plant). Looking at the equations applied, the value must be higher than `Q_CW_min`. And, starting from bottom left and bottom right in the diagram, if both lines meet before reaching the maximum power (`P_max_woDH`), the maximum power will be impossible to reach.
- A `Beta` value that is non-zero. It does not work with a value equal to zero, a very small value works perfectly fine. I would need to check, why zero does not work.

A PQ diagram could then look like this (`Q_CW_max`: 65, `H_L_FG_share_max`: 0.25, `H_L_FG_share_min`: 0.20):

![mchp_Q_CW_max](https://user-images.githubusercontent.com/20252362/109008528-b9968000-76ad-11eb-8f93-63d1bdb47d84.png)

In contrast, the diagram with swapped inputs (`Q_CW_max`: 0, `H_L_FG_share_max`: 0.20, `H_L_FG_share_min`: 0.25) which is equal to the current behavior of the component in the released version.

![mchp](https://user-images.githubusercontent.com/20252362/109008845-15f99f80-76ae-11eb-80d5-dfece3fc9fec.png)

To make this run, you need to install solph from git branch feature/add_Q_CW_max_for_genericCHP.

@simnh, @ckaldemeyer, @uvchik, @p-snft: Could/should this be a new feature? Setting `Q_CW_max` equal to `Q_CW_min` if `Q_CW_max` is not specified by default would prevent that users must adapt all generic CHP models.

**Comment by fwitte** [comment]
I will close this issue as this seems to be a very specific case only, if you don't think so, please feel free to reopen :).
