### ISSUE TITLE
"GenericStorage" simple parameter combinations leads to a infeasible (not solvable) model

### ISSUE THREAD

**Issue by c-franz** [oemof/oemof-solph#784]
Hi,

i used the basic_example.py from the oemof examples at github and changed the parameter settings from the buffer storage component ("GenericStorage").

I found out, that the model is not solvable by the following parameter combinations:
- `initial_storage_level > 0.1 AND balanced = True`
- `initial_storage_level = 0.0 AND balanced = True AND min_storage_level between > 0.0 and < 1.0`
- `initial_storage_level = 0.0 AND balanced = True AND max_storage_level between 0.0 and < 1.0`
- `initial_storage_level = 0.0 AND balanced = True AND many (all?) combinations with the min_storage_level and max_storage_level values`

The example file is attached.

_____________________________________
![generic_storage_model_infeasable](https://user-images.githubusercontent.com/75491027/128474422-777d86dd-1ba9-4446-88b1-34235cd5163e.png)
_____________________________________

I use Python v3.8.11, oemof.solph in the latest release (v0.4.4), pyomo v5.7.2, pandas v1.3.1

[generic_storage_model_infeasible_example.zip](https://github.com/oemof/oemof-solph/files/6944004/generic_storage_model_infeasible_example.zip)

**Comment by uvchik** [comment]
I think we could try to catch inconsistent parameters. If the `initial_storage_level` is lower than the `min_storage_level` or greater than the `max_storage_level` you will get an infeasible model. It would help to check it directly because an infeasible model can have many reasons and is good to exclude the obvious ones as soon as possible. So feel free to add a PR with these checks or an issue with a explaining title if you do not have the time for a PR.

 Of course there are other ways to make a model infeasible. In this example we have a limited gas resource, a volatile feed-in from wind and pv and a fixed demand.  It is just an example an the storage has the right size for this example. If the storage is to small the problem might be infeasible in times when wind and sun is low and the gas resource exhausted. So if you decrease the size of the storage (or add other restrictions) you may have to increase the amount of gas, the installed capacity of wind/pv or whatever you want. If the input does not meet the output the problem will be infeasible.

You could add a shortage Source and an excess Sink. Both can be very expensive, so that they will not be used unless there is no other way to solve your problem. They should be zero in normal cases but if they are not zero you can examine your results to find the reasons, which you cannot do if the model is infeasible.

**Comment by jokochems** [comment]
I find the idea of raising errors for inconsistent parameter combinations for a single component (here a GenericStorage) a good very good one.

(Finding and fixing) Other erroneous combinations will probably remain up to the modeler.

**Comment by p-snft** [comment]
Seems to be solved, I will close this issue.
