### ISSUE TITLE
Example section in the README is still refering to the oemof-example repository

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof-solph#953]
...but should refer to the new integrated examples and give a hint how to download them.

**Comment by p-snft** [comment]
@fwitte: Can you inline the code of the examples n the documentation?

**Comment by fwitte** [comment]
Something which will look like this @p-snft, @uvchik:

![grafik](https://github.com/oemof/oemof-solph/assets/20252362/425f3314-c3b0-4a08-8cf3-8e881110c918)

**Comment by p-snft** [comment]
This looks great! Thanks for the suggestion.

**Comment by fwitte** [comment]
Okay, I pushed the necessary changes for the first example already. Note on that:

The `literalinclude ` directive can be used with `:lines:` (line number specifications) or with (`:starts-after:`/`:ends-before:`) string sequences. The second one would be much nicer, because we do not have to look at line numbers, but since the literalinclude is in the same file we have some kind of literalincludeception, and that version does not work in this specific setup (https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude). The `:pyobject:` variant would skip imports and call of the `main()` function, so no option as well.

Thus, we still need to copy and paste/adjust the section to all other examples.
