### ISSUE TITLE
Determining commission period fails if multi-periods don't have the same length 

### ISSUE THREAD

**Issue by nailend** [oemof/oemof-solph#955]
**Describe the bug**

The constraint to determine the endogenous decommissioning fail in case the periods used in a multi-period approach have not the same length. This is rooted [**here**](https://github.com/oemof/oemof-solph/blob/2b995c9fdf397d5b5cae95bbd83f0e8ec443bc63/src/oemof/solph/components/_generic_storage.py#L1244) for the generic storage component, but probably applies to all other components as well. 

I have three investment periods in my example (2015, 2035, 2050) with the period lengths (0, 20, 15) and a defined component lifetime of 20 years and no initial installed capacity. Solving the example results in the following investment results (see screenshot). In 2015, there is an initial investment (**invest**) of 11.2 MW resulting in a **total** of 11.2 MW. In the next period (20 years later) an investment of 7 MW takes place but 11.2 MW of the existing endogenously installed capacity (**old_end**) is decommissioned, resulting in a **total** of 7 MW. Up to here, all is totally valid. In 2050, however, further decommissioning of 11.2 MW takes place (**old_end**), although there was only 7 MW capacity left  (**total** in 2035). To equal the `_total_storage_capacity_rule` an investment of 11.2 MW has to be done (**invest**).

![image](https://github.com/oemof/oemof-solph/assets/51374526/ce8e6a1c-5c1f-4a8f-9ba3-ffe5877caa0a)

This happens, as in period 2 (2050) the following constraint is generated:
`GenericInvestmentStorageBlock.old_end[el-storage,2]  ==  GenericInvestmentStorageBlock.invest[el-storage,0]`
The wrong commission period is selected. 
although in period 1 this constraint was already defined:
`GenericInvestmentStorageBlock.old_end[el-storage,1]  ==  GenericInvestmentStorageBlock.invest[el-storage,0]`

**To Reproduce**

I found this, implementing the multi-period approach to `oemof.tabular`. I recreated an example in `oemof.solph`:

1.  Checkout branch `reproduce_decomissioning_bug` 
5.  Open `examples/scripting/reproduce_decommissioning_bug.py`
6. Set a breakpoint at line 118, run the script and check the last 2 defined variables.

**Expected behavior**

The expected behavior would be a decommissioning of only 7 MW in 2050.

If you change the year of the last period from 2050 to 2055. Everything works as expected, as the period lengths are now the same.

**Desktop (please complete the following information):**
 -   Ubuntu 20.04 focal
 -   Python 3.10

**Comment by jokochems** [comment]
Hello @nailend,

thank you very much for pointing out that issue and for providing a fix rightaways.

Some remarks here:
* I tried to recreate the oemof.tabular example, but it has changed in the meantime so I was not able to - nevermind, the issue is very well explained and I could understand from looking at the constraint formulations I introduced.
* I was thinking whether there are easier solutions: A boolean switch (as for the exogenously given existing storage investments) as well as breaking the outer for loop in the constraint formulation crossed my mind. But I think they won't suffice since you point out the case with more than one investment being decommissioned in a certain period, right?

Frankly, lifetime tracking and the idea to generalize that to some extend has been the hardest thing to incorporate in the multi-period approach.
