### ISSUE TITLE
Rename "nominal_value" of Flow

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-solph#991]
For `Flow`, we have the keyword `nominal_value`. I think, the capacity of a `Flow` (e.g. a power line) is actually easier to interpret as the "nominal value". Actually, I have been asked that quite some times. If we have a `nominal_capacity` of a `Flow`, it would be arguable why  it's `nominal_storage_capacity` for the `GenericStorage`. So we need to say either `nominal_flow_capacity` which is actually redundant. In my opinion, it makes sense to call both `nominal_capacity`.

In fact, they are quite similar. In particular, they both accept a number (fixed capacity) or an Investment object.

**Comment by upadhayaajay** [comment]
I occasionally find it confusing; using the name nominal_value seems less intuitive. It might make more sense to name it nominal_capacity as you suggested, providing a clearer indication of its meaning. I agree with your suggestion to rename both to nominal_capacity.

_

**Comment by p-snft** [comment]
I still have to keep explaining people what the `nominal_value` is meant for and they just understand if I name it `nominal_capacity`, instead. I think, we should really do this.

**Comment by lensum** [comment]
I agree that `nominal_capacity` would be an easier-to-understand term for the `nominal_value` in the flow. In fact, we already use this term in the documentation of the `full_load_time_max` and `full_load_time_min`. However, I also think that it could be confusing to have `nominal_capacity` describe (simplified) the power of a flow, while the `nominal_storage_capacity` in the `GenericStorage` is an energetic quantity and not a power quantity.
Would it be enough to include good documentation on the `nominal_storage_capacity`? Because I can't think of a better term than "capacity" to describe both quantities (see also this [Wikipedia Article](https://en.wikipedia.org/wiki/Nameplate_capacity) that lists terminology, but most of them end in "capacity"). I guess users that don't read the documentation carefully could be confused. Though maybe this is something we have to live with?

**Comment by p-snft** [comment]
I guess that users that do not consciously distinct power and energy will stumble upon the different time index at some point. In my opinion, the new introductions (#1141) should be very distinct here. Also, the new result processing (cf. #1138) might make the difference clearer by not using these different types of data with the same index (that they in fact do not share).
