### ISSUE TITLE
Multiple outputs for offsetConverter

### ISSUE THREAD

**Issue by drmattimoli** [oemof/oemof-solph#996]
Considering the Converter class implementation, is there a reason for the offsetConverter to not be able to provide multiple outputs? This could be very useful, e.g. when augmenting an existing energysystem implementation with partload efficiency.

**Comment by p-snft** [comment]
Hi @drmattimoli, I really see the point. Here is a bit of background:

The `Converter` relates all inputs with all outputs. This is only possible because the relations are linear without an offset. In principle, it was possible to have one input but multiple outputs for the `OffsetConverter`. So, the `Converter` can do N:M connections with arbitrary N, M. The `OffsetConverter` could do 1:M, if we implemented that. However, you achieve exactly the same by using multiple `OffsetConverter`s sharing the same `Converter` as their source. For M:1 conversion, you will always have do it that way. So, for the sake of consistence, `OffsetConverter` can only do 1:1.
